version: '3.7'

services:
  generator:
    build: '.'
    ports:
      - 9081:9081

  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    environment:
      GEN_ADDRESS: generator
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: