server.port: 9081
project:
  title: order generator
  description: generate orders
spring.application.name: orderGenerator



management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

